//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFBuffBot.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFBuffBot.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 同意报价成功, 无需两步验证, ID: {0} 的本地化字符串。
        /// </summary>
        internal static string AcceptTradeSuccess {
            get {
                return ResourceManager.GetString("AcceptTradeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同意报价成功, 需要两步验证, ID: {0} 的本地化字符串。
        /// </summary>
        internal static string AcceptTradeSuccess2FaRequired {
            get {
                return ResourceManager.GetString("AcceptTradeSuccess2FaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经开启自动发货功能 的本地化字符串。
        /// </summary>
        internal static string AlreadyEnabledBuff {
            get {
                return ResourceManager.GetString("AlreadyEnabledBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经是最新版本, 无需更新插件 的本地化字符串。
        /// </summary>
        internal static string AlreadyLatest {
            get {
                return ResourceManager.GetString("AlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受 的本地化字符串。
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册失败 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterFailed {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册成功 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterSuccess {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动登录Buff失败, 请使用命令 ENABLEBUFF {0} 重新登录 的本地化字符串。
        /// </summary>
        internal static string AutoLoginFailedNeedCode {
            get {
                return ResourceManager.GetString("AutoLoginFailedNeedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动登录Buff成功 的本地化字符串。
        /// </summary>
        internal static string AutoLoginSuccess {
            get {
                return ResourceManager.GetString("AutoLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 被禁用, 可能需要重新登录 Buff 的本地化字符串。
        /// </summary>
        internal static string BotDisabledBuff {
            get {
                return ResourceManager.GetString("BotDisabledBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BotInterval值过小, 推荐设定为30或者更大的值 的本地化字符串。
        /// </summary>
        internal static string BotIntervalWarn {
            get {
                return ResourceManager.GetString("BotIntervalWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BuffNotification网络请求失败, Code: {0} 的本地化字符串。
        /// </summary>
        internal static string BotNotificationRequestFailedSkip {
            get {
                return ResourceManager.GetString("BotNotificationRequestFailedSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置启用自动发货的机器人, 插件将不会工作 的本地化字符串。
        /// </summary>
        internal static string BuffBotNotSetWarn1 {
            get {
                return ResourceManager.GetString("BuffBotNotSetWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令 ENABLEBUFF [Bots] 来为机器人启用自动发货 的本地化字符串。
        /// </summary>
        internal static string BuffBotNotSetWarn2 {
            get {
                return ResourceManager.GetString("BuffBotNotSetWarn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BuffCheckInterval值过小, 推荐设定为180或者更大的值 的本地化字符串。
        /// </summary>
        internal static string BuffCheckIntervalWarn {
            get {
                return ResourceManager.GetString("BuffCheckIntervalWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件初始化完成, 第一次Buff发货检测将于30秒后进行 的本地化字符串。
        /// </summary>
        internal static string BuffCheckWillStartIn30 {
            get {
                return ResourceManager.GetString("BuffCheckWillStartIn30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cookies无效, 请检查Buff是否登录以及Cookies是否完整 的本地化字符串。
        /// </summary>
        internal static string BuffCookiesInvalid {
            get {
                return ResourceManager.GetString("BuffCookiesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cookies有效 的本地化字符串。
        /// </summary>
        internal static string BuffCookiesValid {
            get {
                return ResourceManager.GetString("BuffCookiesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到共有 {0} 个Csgo订单, {1} 个Dota2订单等待发货 的本地化字符串。
        /// </summary>
        internal static string BuffDeliverCount {
            get {
                return ResourceManager.GetString("BuffDeliverCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到共有 {0} 个物品等待发货 的本地化字符串。
        /// </summary>
        internal static string BuffDeliverItemCount {
            get {
                return ResourceManager.GetString("BuffDeliverItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buff登录 {0}, 交易缓存数 {1}, 自动发货接受/拒绝交易数 {2}/{3}, 信息 {4} 的本地化字符串。
        /// </summary>
        internal static string BuffStatus {
            get {
                return ResourceManager.GetString("BuffStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BuffSteamTrade网络请求失败, Code: {0} 的本地化字符串。
        /// </summary>
        internal static string BuffSteamTradeRequestFailed {
            get {
                return ResourceManager.GetString("BuffSteamTradeRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应为空 的本地化字符串。
        /// </summary>
        internal static string CartEmptyResponse {
            get {
                return ResourceManager.GetString("CartEmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份已经自动清理 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackup {
            get {
                return ResourceManager.GetString("CleanUpOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份清理失败 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackupFailed {
            get {
                return ResourceManager.GetString("CleanUpOldBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同意交易报价失败 (一般不要紧) 的本地化字符串。
        /// </summary>
        internal static string ConfirmTradeFailed {
            get {
                return ResourceManager.GetString("ConfirmTradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同意报价失败, ID: {0} 的本地化字符串。
        /// </summary>
        internal static string ConfitmTradeFailed {
            get {
                return ResourceManager.GetString("ConfitmTradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cookies {0}, 交易缓存数: {1} 的本地化字符串。
        /// </summary>
        internal static string CookiesAndTradeCacheCount {
            get {
                return ResourceManager.GetString("CookiesAndTradeCacheCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cookies未设置 的本地化字符串。
        /// </summary>
        internal static string CookiesNotSet {
            get {
                return ResourceManager.GetString("CookiesNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cookies有效, 但是找不到匹配的机器人, 添加失败 的本地化字符串。
        /// </summary>
        internal static string CookiesValidButNoBotFound {
            get {
                return ResourceManager.GetString("CookiesValidButNoBotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前Cookies无效, 请重新设置 的本地化字符串。
        /// </summary>
        internal static string CurrentCookiesInvalid {
            get {
                return ResourceManager.GetString("CurrentCookiesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置Cookies 的本地化字符串。
        /// </summary>
        internal static string CurrentCookiesNotSet {
            get {
                return ResourceManager.GetString("CurrentCookiesNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前Cookies有效 的本地化字符串。
        /// </summary>
        internal static string CurrentCookiesValid {
            get {
                return ResourceManager.GetString("CurrentCookiesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-Hans 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭自动发货功能成功, 自动清空交易缓存和交易统计 的本地化字符串。
        /// </summary>
        internal static string DisableBuffSuccess {
            get {
                return ResourceManager.GetString("DisableBuffSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录Buff失败, 可能该账号 {0} 未注册Buff账号 的本地化字符串。
        /// </summary>
        internal static string EnableBuffFailed {
            get {
                return ResourceManager.GetString("EnableBuffFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录Buff需要验证手机, 验证码已发送, 使用命令 VERIFYCODE {0} xxxx 完成登录 (xxxx 请替换成收到的验证码) 的本地化字符串。
        /// </summary>
        internal static string EnableBuffNeedCode {
            get {
                return ResourceManager.GetString("EnableBuffNeedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录Buff失败, 发送短信验证码失败 的本地化字符串。
        /// </summary>
        internal static string EnableBuffSendCodeFailed {
            get {
                return ResourceManager.GetString("EnableBuffSendCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录Buff成功, 开启自动发货功能 的本地化字符串。
        /// </summary>
        internal static string EnableBuffSuccess {
            get {
                return ResourceManager.GetString("EnableBuffSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启用自动发货, 但是当前机器人离线 的本地化字符串。
        /// </summary>
        internal static string EnabledButOffline {
            get {
                return ResourceManager.GetString("EnabledButOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货检查结束 的本地化字符串。
        /// </summary>
        internal static string EndDeliverCheck {
            get {
                return ResourceManager.GetString("EndDeliverCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查发货遇到错误 的本地化字符串。
        /// </summary>
        internal static string ErrorDeliverCheck {
            get {
                return ResourceManager.GetString("ErrorDeliverCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取Buff待发货订单失败 的本地化字符串。
        /// </summary>
        internal static string FetchBuffDeliverFailed {
            get {
                return ResourceManager.GetString("FetchBuffDeliverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取Buff交易通知失败 的本地化字符串。
        /// </summary>
        internal static string FetchBuffNotificationFailed {
            get {
                return ResourceManager.GetString("FetchBuffNotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件内部数据错误 的本地化字符串。
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易前库存状态: 的本地化字符串。
        /// </summary>
        internal static string InventoryStatusBeforeTrade {
            get {
                return ResourceManager.GetString("InventoryStatusBeforeTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ========================================== 的本地化字符串。
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络异常, 读取库存信息失败 的本地化字符串。
        /// </summary>
        internal static string LoadInventoryFailedNetworkError {
            get {
                return ResourceManager.GetString("LoadInventoryFailedNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行结果: 的本地化字符串。
        /// </summary>
        internal static string MultipleLineResult {
            get {
                return ResourceManager.GetString("MultipleLineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人尚未启用2FA验证, 无法开启自动发货功能 的本地化字符串。
        /// </summary>
        internal static string Need2FaToEnableBuff {
            get {
                return ResourceManager.GetString("Need2FaToEnableBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络错误 的本地化字符串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前Bot未设置两步验证令牌, 跳过执行 的本地化字符串。
        /// </summary>
        internal static string No2FaSetSkip {
            get {
                return ResourceManager.GetString("No2FaSetSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置下无可显示的内容 的本地化字符串。
        /// </summary>
        internal static string NoAvilableItemToShow {
            get {
                return ResourceManager.GetString("NoAvilableItemToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到可用的机器人, 添加失败 的本地化字符串。
        /// </summary>
        internal static string NoBotAvilable {
            get {
                return ResourceManager.GetString("NoBotAvilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置有效的 BuffCookies, 跳过执行 的本地化字符串。
        /// </summary>
        internal static string NoBuffCookiesSkip {
            get {
                return ResourceManager.GetString("NoBuffCookiesSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无信息 的本地化字符串。
        /// </summary>
        internal static string NoInformation {
            get {
                return ResourceManager.GetString("NoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无等待自动发货的物品 的本地化字符串。
        /// </summary>
        internal static string NoItemToDeliver {
            get {
                return ResourceManager.GetString("NoItemToDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到匹配的交易报价, 可能交易报价已取消, Id: {0} 的本地化字符串。
        /// </summary>
        internal static string NoMatchTradeFound {
            get {
                return ResourceManager.GetString("NoMatchTradeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未开启自动发货功能 的本地化字符串。
        /// </summary>
        internal static string NotEnabledBuff {
            get {
                return ResourceManager.GetString("NotEnabledBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前机器人未登录, 跳过执行 的本地化字符串。
        /// </summary>
        internal static string NotLoginSkip {
            get {
                return ResourceManager.GetString("NotLoginSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无Trade缓存信息, 跳过执行 的本地化字符串。
        /// </summary>
        internal static string NoTradeCacheSkip {
            get {
                return ResourceManager.GetString("NoTradeCacheSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 Chr_, 联系方式 chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱发电: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐安装 ASFEnhance, 支持自动更新插件 的本地化字符串。
        /// </summary>
        internal static string PluginStandalongMode {
            get {
                return ResourceManager.GetString("PluginStandalongMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取Cookies文件出错 的本地化字符串。
        /// </summary>
        internal static string ReadCookiesFailed {
            get {
                return ResourceManager.GetString("ReadCookiesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到新交易, ID:{0} 的本地化字符串。
        /// </summary>
        internal static string ReceivedNewTradeCache {
            get {
                return ResourceManager.GetString("ReceivedNewTradeCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册Buff Service失败 的本地化字符串。
        /// </summary>
        internal static string RegisterBuffServiceFailed {
            get {
                return ResourceManager.GetString("RegisterBuffServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝 的本地化字符串。
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拒绝交易{0}, Id: {1} 的本地化字符串。
        /// </summary>
        internal static string RejectTrade {
            get {
                return ResourceManager.GetString("RejectTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易报价发送{0} 的本地化字符串。
        /// </summary>
        internal static string SendTradeResult {
            get {
                return ResourceManager.GetString("SendTradeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始为 {0} 检查发货信息 的本地化字符串。
        /// </summary>
        internal static string StartDeliverCheck {
            get {
                return ResourceManager.GetString("StartDeliverCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamId 无效 的本地化字符串。
        /// </summary>
        internal static string SteamIdInvalid {
            get {
                return ResourceManager.GetString("SteamIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}交易报价{1}, Msg: {2}, Id: {3} 的本地化字符串。
        /// </summary>
        internal static string SteamTradeDetail {
            get {
                return ResourceManager.GetString("SteamTradeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 链接: {0} 的本地化字符串。
        /// </summary>
        internal static string SubLink {
            get {
                return ResourceManager.GetString("SubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 名称: {0} 的本地化字符串。
        /// </summary>
        internal static string SubName {
            get {
                return ResourceManager.GetString("SubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 尺寸: {0:0.000} KB 的本地化字符串。
        /// </summary>
        internal static string SubSize {
            get {
                return ResourceManager.GetString("SubSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 已初始化缓存, 无法初始化交易缓存 的本地化字符串。
        /// </summary>
        internal static string TradeCacheAlreadyInit {
            get {
                return ResourceManager.GetString("TradeCacheAlreadyInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 未初始化缓存, 无法记录交易 的本地化字符串。
        /// </summary>
        internal static string TradeCacheNotInit {
            get {
                return ResourceManager.GetString("TradeCacheNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 未初始化缓存, 无法清空交易缓存 的本地化字符串。
        /// </summary>
        internal static string TradeCacheNotInitCantClear {
            get {
                return ResourceManager.GetString("TradeCacheNotInitCantClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易已完成, ID: {0} =&gt; {1} 的本地化字符串。
        /// </summary>
        internal static string TradeComplete {
            get {
                return ResourceManager.GetString("TradeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易物品不匹配, Id: {0} 的本地化字符串。
        /// </summary>
        internal static string TradeDismatch {
            get {
                return ResourceManager.GetString("TradeDismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易物品不匹配, 自动拒绝报价, Id: {0} 的本地化字符串。
        /// </summary>
        internal static string TradeDismatchAutoReject {
            get {
                return ResourceManager.GetString("TradeDismatchAutoReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易物品匹配, 自动发货, Id: {0} 的本地化字符串。
        /// </summary>
        internal static string TradeMatchAtuoAccept {
            get {
                return ResourceManager.GetString("TradeMatchAtuoAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string TwoItem {
            get {
                return ResourceManager.GetString("TwoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新交易, ID: {0} 的本地化字符串。
        /// </summary>
        internal static string UpdateTradeCache {
            get {
                return ResourceManager.GetString("UpdateTradeCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证Buff手机号 {0}, 登录Buff {1} 的本地化字符串。
        /// </summary>
        internal static string VerifyCodeAndLoginStatus {
            get {
                return ResourceManager.GetString("VerifyCodeAndLoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先使用命令 ENABLEBUFF {0} 登录Buff, 如果需要输入验证码再使用此命令 的本地化字符串。
        /// </summary>
        internal static string VerifyCodeNeedLoginFirst {
            get {
                return ResourceManager.GetString("VerifyCodeNeedLoginFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入Cookies文件出错 的本地化字符串。
        /// </summary>
        internal static string WriteCookiesFailed {
            get {
                return ResourceManager.GetString("WriteCookiesFailed", resourceCulture);
            }
        }
    }
}
