//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFBuffBot.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASFBuffBot.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当前已经是最新版本, 无需更新插件 的本地化字符串。
        /// </summary>
        internal static string AlreadyLatest {
            get {
                return ResourceManager.GetString("AlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFECurrentVersion {
            get {
                return ResourceManager.GetString("ASFECurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFEOnlineVersion {
            get {
                return ResourceManager.GetString("ASFEOnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 插件版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ASFEPluginVersion {
            get {
                return ResourceManager.GetString("ASFEPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令 ASFEUPDATE / AU 自动更新插件 的本地化字符串。
        /// </summary>
        internal static string ASFEUpdateTips {
            get {
                return ResourceManager.GetString("ASFEUpdateTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令 ASFEVERSION / AV 检查插件更新 的本地化字符串。
        /// </summary>
        internal static string ASFEVersionTips {
            get {
                return ResourceManager.GetString("ASFEVersionTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 附件:  的本地化字符串。
        /// </summary>
        internal static string Assert {
            get {
                return ResourceManager.GetString("Assert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 响应为空 的本地化字符串。
        /// </summary>
        internal static string CartEmptyResponse {
            get {
                return ResourceManager.GetString("CartEmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份已经自动清理 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackup {
            get {
                return ResourceManager.GetString("CleanUpOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的插件备份清理失败 的本地化字符串。
        /// </summary>
        internal static string CleanUpOldBackupFailed {
            get {
                return ResourceManager.GetString("CleanUpOldBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh-Hans 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 描述: {0} 的本地化字符串。
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载插件失败! 的本地化字符串。
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - Access: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogAccess {
            get {
                return ResourceManager.GetString("ErrorLogAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - ASF 版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogASFVersion {
            get {
                return ResourceManager.GetString("ErrorLogASFVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 错误消息: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogErrorMessage {
            get {
                return ResourceManager.GetString("ErrorLogErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 错误类型: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogErrorName {
            get {
                return ResourceManager.GetString("ErrorLogErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 原始消息: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogOriginMessage {
            get {
                return ResourceManager.GetString("ErrorLogOriginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 插件版本: {0} 的本地化字符串。
        /// </summary>
        internal static string ErrorLogPluginVersion {
            get {
                return ResourceManager.GetString("ErrorLogPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFBuffBot 遇到错误, 日志如下 的本地化字符串。
        /// </summary>
        internal static string ErrorLogTitle {
            get {
                return ResourceManager.GetString("ErrorLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取插件发行版信息失败! 的本地化字符串。
        /// </summary>
        internal static string GetReleaseInfoFailed {
            get {
                return ResourceManager.GetString("GetReleaseInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易前库存状态: 的本地化字符串。
        /// </summary>
        internal static string InventoryStatusBeforeTrade {
            get {
                return ResourceManager.GetString("InventoryStatusBeforeTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络异常, 读取库存信息失败 的本地化字符串。
        /// </summary>
        internal static string LoadInventoryFailedNetworkError {
            get {
                return ResourceManager.GetString("LoadInventoryFailedNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行结果: 的本地化字符串。
        /// </summary>
        internal static string MultipleLineResult {
            get {
                return ResourceManager.GetString("MultipleLineResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络错误 的本地化字符串。
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置下无可显示的内容 的本地化字符串。
        /// </summary>
        internal static string NoAvilableItemToShow {
            get {
                return ResourceManager.GetString("NoAvilableItemToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无信息 的本地化字符串。
        /// </summary>
        internal static string NoInformation {
            get {
                return ResourceManager.GetString("NoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 Chr_, 联系方式 chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱发电: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 版本 {1} 的本地化字符串。
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易报价发送{0} 的本地化字符串。
        /// </summary>
        internal static string SendTradeResult {
            get {
                return ResourceManager.GetString("SendTradeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamId 无效 的本地化字符串。
        /// </summary>
        internal static string SteamIdInvalid {
            get {
                return ResourceManager.GetString("SteamIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 链接: {0} 的本地化字符串。
        /// </summary>
        internal static string SubLink {
            get {
                return ResourceManager.GetString("SubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 名称: {0} 的本地化字符串。
        /// </summary>
        internal static string SubName {
            get {
                return ResourceManager.GetString("SubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    - 尺寸: {0:0.000} KB 的本地化字符串。
        /// </summary>
        internal static string SubSize {
            get {
                return ResourceManager.GetString("SubSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        internal static string TwoItem {
            get {
                return ResourceManager.GetString("TwoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新失败, 压缩包内容解析失败 的本地化字符串。
        /// </summary>
        internal static string UpdateFiledWithZip {
            get {
                return ResourceManager.GetString("UpdateFiledWithZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新完成, 重启ASF即可应用, 如果不兼容请更新ASF版本 的本地化字符串。
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以使用命令 ASFEUPDATE / AU 自动更新插件 的本地化字符串。
        /// </summary>
        internal static string UpdateTips {
            get {
                return ResourceManager.GetString("UpdateTips", resourceCulture);
            }
        }
    }
}
